version: '3'

services:
  nginx-rtmp:
    build: .
    container_name: stream-server
    restart: unless-stopped
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    volumes:
      - ./certs:/opt/certs
    environment:
      - FILESYSTEM=${FILESYSTEM}
      - AWS_S3_URL=${AWS_S3_URL}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}